### PR TITLE
store preferences in ManagedInstalls

### PR DESCRIPTION
**Pull request by discentem**

### CODE REVIEW

**Comment by erikng** [comment]
The reason for this is an admin can provide a single mobileconfig and manage these settings. Also some companies don't like when profiles are installing with people's names. :)

**Comment by discentem** [comment]
I just thought of a potential problem with my change. If Munki settings are enforced via profile, a user can read the `AccessKey`/`SecretKey` easily in Sys Prefs, no?

**Comment by erikng** [comment]
This would be no difference than it is now.

Thanks,
Erik Gomez
________________________________

**Comment by waderobson** [comment]
This all seems reasonable. I just wanna test it first. I should have time this week. 

As long as folks scope the IAM policy right it shouldn't matter if they see the credentials.
If people want to hide them, you can still add them to root user's preferences(where they can still be found by admins).  I suppose the only way around that is to obfuscate them some how, but in reality you would only be preventing folks from downloading everything from munki.

**Comment by discentem** [comment]
Cool. Thanks @waderobson

**Pull request merged**
